/** biome-ignore-all lint/a11y/useHtmlLang: <explanation> */
import type { Metadata } from 'next';
import { Victor_Mono } from 'next/font/google';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import './globals.css';
import { notFound } from 'next/navigation';
import { getTranslations, setRequestLocale } from 'next-intl/server';
import type { ReactNode } from 'react';
import PageHeader from '@/components/molecules/PageHeader/PageHeader';
import { routing } from '@/i18n/routing';

const victorMono = Victor_Mono({
  variable: '--font-victor-mono',
  subsets: ['latin'],
  style: ['normal', 'italic'],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Hendrik Peter',
//   description: 'Generated by create next app',
// };

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

export const createSticParams = async () => {
  return routing.locales.map((locale) => ({ locale }));
};

export const generateMetadata = async ({ params }: Props): Promise<Metadata> => {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations('RootLayout');

  return {
    title: t('pageTitle'),
    description: t('pageDescription'),
  };
};

export default async function RootLayout({ params, children }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  return (
    <html>
      <body className={`${victorMono.variable} antialiased`}>
        <NextIntlClientProvider>
          <div className="flex flex-col gap-4 min-h-screen">
            <PageHeader />
            <div className="flex-1 px-8">{children}</div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
